DELETE http://localhost:3001/api/blogs/65ac1f2afb37bb34cfe29615
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFpcm1hbiIsImlkIjoiNjVhYTFmMzViNjI0MWQ1M2QwNGE0NGU1IiwiaWF0IjoxNzA1NjQ5NjY3fQ.WayzrWhTCYIQpA0lwcMzdOnH36nsLYZPCS6L4m2NYws

###

DELETE http://localhost:3001/api/blogs/65ac1fdcfb37bb34cfe29622
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvcGhpZWxvdSIsImlkIjoiNjVhYTJmZDM1MzZhMWEwMjU5ZmQ2YWIxIiwiaWF0IjoxNzA1Nzc4OTQyLCJleHAiOjE3MDU3ODI1NDJ9.hv2vWEDWFrXq02NMEDkqQOXCM_rRnvhbaX8GzHMGySA